version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps)"
    versioning-strategy: increase
    groups:
      all:
        patterns:
          - "*"
