version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      include: scope
      prefix-development: chore
    versioning-strategy: increase
    groups:
      all:
        patterns:
          - "*"
