# Taken from obytes' react native template: https://github.com/obytes/react-native-template-obytes

name: "Setup  Node + PNPM + Install Dependencies"
description: "Setup  Node + PNPM + Install Dependencies"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        cache: "pnpm"

    - name: 📦 Install Project Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
