import type { ConsoleToken } from "@glyphide/quickjs-engine/types";
import type { RenderedOutput } from "../core/engine/output-formatter.ts";
import type { OutputEntry } from "../core/models/output.ts";

/**
 * Represents a normalized, single-level console entry derived from the nested console hierarchy.
 *
 * Intent: This structure is consumed by the VirtualList to achieve O(N) rendering.
 * By computing depth, visibility, and collapse states ahead of time, we avoid
 * complex tree traversals during the render loop.
 *
 * Edge cases: Items completely hidden within collapsed groups are omitted entirely
 * from the flat list, ensuring they do not occupy virtual layout space.
 *
 * Side effects: None (this is purely a data representation).
 */
export interface FlatConsoleItem {
  /** Depth in the group hierarchy */
  depth: number;
  /** The original raw output entry received from the engine */
  entry: OutputEntry;
  /** Optional tokens for group labels */
  groupLabel?: ConsoleToken[];
  /** Unique ID for the item (typically its original index) */
  id: number;
  /** True if this is a group and it is currently collapsed */
  isCollapsed: boolean;
  /** True if this item represents a console.group or console.groupCollapsed */
  isGroup: boolean;
  /** The formatted output generated by the output formatter */
  rendered: RenderedOutput;
}

function processConsoleEntry(
  i: number,
  formattedEntry: { entry: OutputEntry; rendered: RenderedOutput },
  isGroupCollapsed: (id: number, startsCollapsed: boolean) => boolean,
  visibleItems: FlatConsoleItem[],
  groupStack: { id: number; hidden: boolean }[],
  oldItemMap?: Map<number, FlatConsoleItem>
) {
  const { entry, rendered } = formattedEntry;
  const variant = rendered.variant;

  if (variant === "groupEnd") {
    if (groupStack.length > 0) {
      groupStack.pop();
    }
    return;
  }

  const parent = groupStack.at(-1);
  const parentIsHidden = parent ? parent.hidden : false;

  if (parentIsHidden) {
    // Even if hidden, if this is a group we must push it to the stack
    // to ensure its corresponding groupEnd pops correctly.
    if (variant === "group" || variant === "groupCollapsed") {
      groupStack.push({ id: i, hidden: true });
    }
    return;
  }

  const isGroup = variant === "group" || variant === "groupCollapsed";
  const startsCollapsed = variant === "groupCollapsed";
  let isCollapsed = false;

  if (isGroup) {
    isCollapsed = isGroupCollapsed(i, startsCollapsed);
  }

  const depth = groupStack.length;
  const oldItem = oldItemMap?.get(i);

  if (
    oldItem &&
    oldItem.depth === depth &&
    oldItem.isGroup === isGroup &&
    oldItem.isCollapsed === isCollapsed
  ) {
    visibleItems.push(oldItem);
  } else {
    visibleItems.push({
      id: i,
      entry,
      rendered,
      depth,
      isGroup,
      isCollapsed,
      groupLabel: isGroup
        ? ((rendered.tokens as ConsoleToken[]) ?? [])
        : undefined,
    });
  }

  if (isGroup) {
    groupStack.push({ id: i, hidden: isCollapsed });
  }
}

/**
 * Transforms a flat list of formatted console entries into a flattened list of visible items,
 * skipping items that are hidden inside collapsed groups.
 *
 * Intent: To build a 1D array suitable for virtualized rendering from a simulated nested structure.
 *
 * Edge cases:
 * - Items deep inside multiple nested groups will be hidden if ANY parent is collapsed.
 * - Missing `groupEnd` calls are tolerated (groups remain implicitly open to the end).
 *
 * Side effects: Modifies the provided `visibleItems` array and `groupStack` arrays directly for performance,
 * pushing new items and popping hidden states without creating new arrays.
 *
 * @param formattedEntries The full list of formatted entries
 * @param isGroupCollapsed A callback to resolve whether a specific group is currently collapsed
 * @param startIndex The index to start processing from (for incremental updates)
 * @param visibleItems The existing mutable array of visible items
 * @param groupStack The existing mutable stack of open groups
 */
export function flattenConsoleEntries(
  formattedEntries: ReadonlyArray<{
    entry: OutputEntry;
    rendered: RenderedOutput;
  }>,
  isGroupCollapsed: (id: number, startsCollapsed: boolean) => boolean,
  startIndex = 0,
  visibleItems: FlatConsoleItem[] = [],
  groupStack: { id: number; hidden: boolean }[] = []
): FlatConsoleItem[] {
  let oldItemMap: Map<number, FlatConsoleItem> | undefined;

  if (startIndex === 0) {
    oldItemMap = new Map();
    for (const item of visibleItems) {
      oldItemMap.set(item.id, item);
    }
    visibleItems.length = 0;
    groupStack.length = 0;
  }

  for (let i = startIndex; i < formattedEntries.length; i++) {
    processConsoleEntry(
      i,
      formattedEntries[i],
      isGroupCollapsed,
      visibleItems,
      groupStack,
      oldItemMap
    );
  }

  return visibleItems;
}
