name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-pnpm-install

      - name: Run Lint (PR)
        if: github.event_name == 'pull_request'
        uses: mongolyy/reviewdog-action-biome@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: Run Lint (Commit)
        if: github.event_name != 'pull_request'
        run: pnpm run lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node-pnpm-install

      - name: Run Type Check
        run: pnpm tsc

  astro:
    name: Astro Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node-pnpm-install

      - run: pnpm check